# -*- coding: utf-8 -*-
"""Data Structure - Set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAAD92emeyGctupmmYv4o_BuR1luSBhm
"""

#add() method is used to add a single element to a set.
numbers = {10, 20, 30}
(numbers.add(500))
print(numbers)

#Tuples are immutable, so they can be added to a set.
data = {1, 2, 3}
data.add((4, 5))
print(data)

#Lists are mutable and therefore unhashable.
data = {1, 2, 3}
data.add([4, 5])
print(data)

#update() method is used to add multiple elements to a set.
'''set_name.update(iterable)'''

numbers = {1, 2, 3}
numbers.update([4, 5, 6])
print(numbers)

numbers = {1, 2, 3}
numbers.update((4, 5))
print(numbers)

s1 = {1, 2, 3}
s2 = {3, 4, 5}
s1.update(s2)
print(s1)

letters = {"a", "b"}
letters.update("cde")
print(letters)

#pop() method removes and returns an arbitrary (random) element from a set.
#Sets do not maintain indexing like lists, so any item can be removed randomly

numbers = {10, 20, 30}
value = numbers.pop()
print(value)
print(numbers)


fruits = {"apple", "banana", "orange"}
removed = fruits.pop()
print("Removed:", removed)
print("Remaining:", fruits)

#clear() method removes all elements from a set, making it empty.
numbers = {10, 20, 30, 40}
numbers.clear()
print(numbers)

#copy() method creates a shallow copy of a set
#new_set = original_set.copy()
#copy() takes no auguments

numbers = {10, 20, 30}
new_numbers = numbers.copy()
print(numbers)
print(new_numbers)

#remove() method is used to remove a specific element from a set.

numbers = {10, 20, 30}
numbers.remove(20)
print(numbers)

numbers = {10, 20, 30}
numbers.remove(40) #remove() raises a KeyError if the element does not exist.

#discard() method removes a specified element from a set.
numbers = {10, 20, 30}
numbers.discard(20)
print(numbers)

numbers = {10, 20, 30}
result = numbers.discard(20)
print(result)

#If no value is present, No error is raised & The set remains unchanged.
#Returns none

#union() method returns a new set containing all unique elements from two or more sets.
set1 = {1, 2}
set2 = {2, 3}
set3 = {3, 4}
result = set1.union(set2, set3)
print(result)

#print(set1 | set2) - This is same for above

set1 = {1, 2, 3}
set2 = {3, 4, 5}
result = set1.union(set2)
print(set1)
print(result) #Original sets are not modified

#intersection() method returns the common elements present in both sets.
set1 = {1, 2, 3, 4}
set2 = {2, 3, 5}
set3 = {2, 3, 6}
result = set1.intersection(set2, set3)
print(result)

set1 = {1, 2, 3}
set2 = {2, 3, 4}
print(set1 & set2) #This is same as above

set1 = {1, 2}
set2 = {3, 4}
print(set1.intersection(set2)) #An empty set means there are no common elements.

#intersection_update()
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
set1.intersection_update(set2)
print(set1) #Modifies the original set

#difference() method returns the elements that are present in the first set
#but not in the second set.
#set1.difference(set2)
#set1 - set2

set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
result = set1.difference(set2)
print(result)

set1 = {1, 2, 3}
set2 = {2, 3, 4}
print(set1 - set2)
set1 = {1, 2, 3}
set2 = {2, 3, 4}
print(set1 - set2)
print(set2 - set1)

set1 = {1, 2, 3, 4, 5}
set2 = {2, 3}
set3 = {5}
result = set1.difference(set2, set3)
print(result)

#symmetric_difference() method returns elements that are present in either set, but not in both.
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}
result = set1.symmetric_difference(set2)
print(result)

set1 = {1, 2, 3}
set2 = {3, 4, 5}
print(set1 ^ set2)

#No common elements, Returns all.
set1 = {1, 2}
set2 = {3, 4}
print(set1.symmetric_difference(set2))

#Same elements, Returns nothing
set1 = {1, 2, 3}
set2 = {1, 2, 3}
print(set1.symmetric_difference(set2))

#issubset() method checks whether all elements of one set are present in another set.
#Output Boolean
set1 = {1, 2}
set2 = {1, 2, 3, 4}
print(set1.issubset(set2))

set1 = {1, 2, 5}
set2 = {1, 2, 3, 4}
print(set1.issubset(set2))

set1 = {1, 2}
set2 = {1, 2, 3}
print(set1 <= set2)

#issuperset() method checks whether all elements of another set are present in the current set.
#Boolean output

a = {1, 2, 3, 4}
b = {1, 2}
print(a.issuperset(b))

a = {1, 2, 3}
b = {1, 2, 4}
print(a.issuperset(b))

a = {1, 2, 3, 4}
b = {1, 2}
print(a >= b)

#isdisjoint() method checks whether two sets have no common elements.
#Boolean output
set1 = {1, 2, 3}
set2 = {4, 5, 6}
print(set1.isdisjoint(set2)) #True

set1 = {1, 2, 3}
set2 = {3, 4, 5}
print(set1.isdisjoint(set2)) #False